---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ks-workbox
spec:
  accessModes: [ 'ReadWriteOnce' ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: workbox
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: workbox
    spec:
      serviceAccountName: kubeflow-deployer
      serviceAccount: kubeflow-deployer
      containers:
      - image:  quay.io/rbo/redhathackathon-kubeflow-deployer
        name: workbox
        command: [ "/bin/sh", "-c", "/deployer/workbox.sh" ]
        volumeMounts:
          - mountPath: /workspace
            name: ks-workbox
      dnsPolicy: ClusterFirst
      initContainers:
      - name: kubeflow-deploy
        image: quay.io/rbo/redhathackathon-kubeflow-deployer
        command: ['sh', '-c', '/deployer/kubeflow-deploy.sh']
        volumeMounts:
          - mountPath: /workspace
            name: ks-workbox
      volumes:
        - name: ks-workbox
          persistentVolumeClaim:
            claimName: ks-workbox
  triggers:
  - type: ConfigChange
